version: '3.8'
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: '12345'
        ports:
            - 3307:3307  # Changed the host port to 3307 to avoid conflicts
        volumes:
            - mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 8080:8080
volumes:
    mysql_data: {}